### ISSUE TITLE
Auto indent 'end' keyword

### ISSUE THREAD

**Issue by quinnj** [JuliaEditorSupport/julia-vscode#204] opened 2017-07-13 04:57 UTC
Just a little thing that I grew really used to using Atom, the behavior is that when you're typing things like:
```julia
function foo()

    end
```
the `end` would get auto indented to match the `function` indentation. This becomes super handy when you're dealing w/ lots of nested if, for, while, being, whatever blocks.

Just a little thing, but it'd be really nice.

**Comment by davidanthoff** [comment] 2017-07-14 08:24
Duplicate of #37. This might actually work on VS Code insider builds (and if it does, it would show up in the next monthly release of VS Code).

**Closed by davidanthoff** 2017-07-14 08:24 UTC
Labels: duplicate

**Comment by ZacLN** [comment] 2017-07-14 09:10
This is in vscode , 1.14 which was just released

**Comment by quinnj** [comment] 2017-07-14 12:16
@ZacLN, I think you meant 1.15? I've been running on insider builds and indeed, updating this morning brought in this functionality. Cheers!

**Comment by davidanthoff** [comment] 2017-07-14 12:22
I'm running on regular (not insider), got 1.14 this morning and it works.
