### ISSUE TITLE
No auto indentation for function

### ISSUE THREAD

**Issue by AStupidBear** [JuliaEditorSupport/julia-vscode#151] opened 2017-04-07 11:03 UTC
![2017-04-07_190015](https://cloud.githubusercontent.com/assets/16422976/24797664/d52ce360-1bc4-11e7-93a4-ee1c265ca49d.jpg)

**Comment by ZacLN** [comment] 2017-04-07 11:51
This is an upstream issue with `vscode` #37  which I believe is being worked on/is fixed on the newest versions

**Comment by davidanthoff** [comment] 2017-04-07 16:09
Yes, this is a duplicate of #37.

**Closed by davidanthoff** 2017-04-07 16:09 UTC
