### ISSUE TITLE
can julia-vscode connect with a remote julia interpreter ?

### ISSUE THREAD

**Issue by cailiangliang765** [JuliaEditorSupport/julia-vscode#638] opened 2018-12-25 02:41 UTC
i just wonder can julia-vscode connect with a remote julia interpreter ?

**Comment by davidanthoff** [comment] 2018-12-25 03:40
No, not possible, I'm afraid.

**Comment by cailiangliang765** [comment] 2018-12-26 03:00
> No, not possible, I'm afraid.

thanks for your reply. hoping for adding this function in the future.

**Comment by tribut** [comment] 2019-02-28 12:51
Duplicate of #509

**Comment by joshuamanns** [comment] 2019-04-15 20:01
> No, not possible, I'm afraid.

@davidanthoff Could you shed more light on why this isn't possible? Is it fundamentally incompatible with the way vscode works? Or is there some third-party extension/workaround that could provide a loophole? I know quite a few users who are sticking with Atom because this feature is not yet available.

**Comment by davidanthoff** [comment] 2019-04-15 20:07
No fundamental reason, someone would just have to implement it.

**Closed** 2019-05-12 22:34 UTC
Labels: duplicate, enhancement
