### ISSUE TITLE
Autocomplete/linting for user packages

### ISSUE THREAD

**Issue by colinxs** [JuliaEditorSupport/julia-vscode#660] opened 2019-01-11 17:31 UTC
Hello! I'm having some problems getting autocomplete/linting to work for user packages.

Case 1: Environment Foo has package Bar (a package I wrote and lives in some arbitrary path) installed using Pkg.develop. I edit Bar's source files in VSCode with environment Foo activated. Autocomplete/linting works, but modifications to Bar's source files are not reflected. It appears that the symbol store is being generated once by UUID and is never regenerated due to a change in the source directory. If I delete the .jstore file in SymbolServer corresponding to Bar and reload VSCode then the autocomplete/linting reflects the most recent changes.

Case 2: Editing package Bar with it's Bar environment activated (as in Bar is not installed). No autocomplete/linting works.

Am I missing something here? This is on v 0.11.2. Thanks!

**Comment by davidanthoff** [comment] 2019-01-12 06:30
Our environment story right now is super incomplete. In particular, the environment you pick in the UI has no effect on linting/auto complete etc... We essentially ran out of time, the UI was ready, and then we felt we should just publish the 1.0 compatible version.

It is on the radar, and I know how to fix it, but it is all a bit involved...

**Comment by colinxs** [comment] 2019-01-13 20:08
Thanks for the rapid response! So could you perhaps clarify which version
of julia-vscode I should use and exactly how I should use it (where to
store files, how to setup environment, etc.) such that I can benefit from
linting/autocompletion for both installed packages and packages that I'm
developing? That would be most useful!

Colin X Summers
Paul G. Allen School of Computer Science & Engineering
Robotics and State Estimation Lab
Personal Robotics Lab
www.colinxsummers.com

**Comment by stakaz** [comment] 2019-01-23 12:19
Would be great to hear any news on this issue. It makes the linting nearly unusable for me as I have many custom packages and get tons of warnings from linter about possible undefined variables and functions. Maybe there is already a branch for this?

**Comment by davidanthoff** [comment] 2019-01-24 20:12
No branch, I'm afraid, and no estimate right now when I'll get to finish this.

**Comment by davidanthoff** [comment] 2019-06-12 04:32
I'm going to close this as a duplicate of https://github.com/JuliaEditorSupport/julia-vscode/issues/732. We now have a not fully functional PR that should complete our handling of julia environments in the extension, so my expectation is that this will work with the next release of the extension.

**Closed by davidanthoff** 2019-06-12 04:32 UTC
Labels: area-environments, bug
