### ISSUE TITLE
Use of possibly undeclared variable when using/importing modules

### ISSUE THREAD

**Issue by williamcol3** [JuliaEditorSupport/julia-vscode#718] opened 2019-05-03 13:07 UTC
Hello, thank you for the hard work in creating this extension. I am using Julia 1.1, VSCode 1.33.1, and version 0.11.5 of the extension.

I am currently having problems setting up the Julia extension to work with my code. I have a project environment with the following Project.toml

```
[deps]
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
GZip = "92fee26a-97fe-5a0c-ad85-20a5f3185b63"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
MD5 = "6ac74813-4b46-53a4-afec-0b5dc9d7885c"
```

But the following file

```julia
module DeepNetworks

using Flux

function make_lenet()
    # Input is 28x28 grayscale (1 channel)
    m = Chain(# Size after convolution 24x24
              Conv((5, 5), 1=>16, tanh),
              # Size after pooling is 12x12
              MaxPool((2, 2)),
              # Size after convolution is 8x8
              Conv((5, 5), 16=>32, tanh),
              # Size after pooling is 4x4
              MaxPool((2, 2)),
              x -> reshape(x, 16, :),
              Dense(10),
              softmax)
end # function

end  # module DeepNetworks
```
Gives "Use of possibly undeclared variable: Flux" for that using statement and everything that would be imported by Flux.

I have made sure that everything is installed correctly and working in the REPL, so that isn't the problem. I have tried using the `Julia: change the current environment` to point to the project folder, but that did not work either.

Interestingly, importing LinearAlgebra and using it in the context of a function did work. This leads me to believe the Language Server is somehow not picking up on the environment.

I doubt this is a bug, since this is pretty fundamental and other people are using the extension just fine. What am I missing, and should documentation be improved to help with the set up process?

I appreciate any help that you may have.
---
EDIT

I have done some more experimenting. I first tried installing the HTTP.jl dependency in the base environment (v1.1). I had a hunch this might work since the Symbol server was picking up on the LinearAlgebra symbols. It did indeed and I was able to get auto-completions for the HTTP module.

So the problem appears to be with `Julia: Change the current environment` command. I previously was using the `(pick a folder)` to select the project environment. This appears to not change the environment. I then tried creating a shared environment and selecting it with the command. This also appears to have not changed the activated environment for the auto-completer.

I think we can conclusively say that for some reason this command is not changing the activated environment for the extension.

**Comment by williamcol3** [comment] 2019-05-07 01:22
After digging into the source and the calls into LanguageServer.jl, I have realized as others have that this all stems from a language server implementation problem that `activateenvironment(envname) is a stub.

Perhaps there should be better documentation in this process to signify that only completion for packages in the main version environment is supported until such a time that changing environments is actually supported.

I'll leave it to any maintainers to decide what to do. If desired, I can whip up a PR to edit the README.md to mention such a limitation (or perhaps it should go in the wiki).

**Comment by stakaz** [comment] 2019-05-07 07:12
If this is a limitation which will be valid for a longer time, I would really like to be able to disable the warnings for the "undeclared" variables without loosing the linter completely. Would that be possible?

**Comment by williamcol3** [comment] 2019-05-07 23:14
I think having the warning is better than just silently not auto-completing. That would be really frustrating to diagnose on a first install. I think simple statement in a README is enough. I will workaround this limitation for now using the conda package manager and having a separate conda environment for each project. Then I'll point VS Code to the correct Julia exectuable using folder/workspace settings. Then I just have to keep the install default environment in sync with the project environment. I hope symbol server will be fine with a Depot path that isn't ~/.julia

**Comment by stakaz** [comment] 2019-05-08 08:32
Hey, what I mean is an option to be able to disable the warnings. So that by default they are on but you can disable them once you know, that this is a limitation of the package for now. Could you explain a little bit more how you generate a new environment? Because I actually only use one project environment all the time but still have no auto-completion for packages which are in a separate directory and are loaded through `setup.jl`.

**Comment by williamcol3** [comment] 2019-05-09 01:47
Ah, I understand you now. I personally wouldn't turn them off, but that could be a useful option. 

The language server probably doesn't provide completions for definitions and imports in your `startup.jl` because it does not parse those. Until that is changed, it never will.

It seems like when the language server starts up, it analyses the default environment (v1.0 in my case) for the depot defined by the `JULIA_DEPOT_PATH` environment variable. Thus, to get completions at a point, two conditions must occur:

1. The definitions must be visible at that point (either defined in the file or imported/included)
2. Any imported modules must be a part of the default depot environment (defined in $JULIA_DEPOT_PATH/envs/v1.0/Project.toml in my case)

To get the completions I want (those that correspond exactly to my project) I create a new `conda` environment that has it's own Julia executable (available from conda-forge). I use a workspace setting in VS Code to set this new environment's Julia as the Julia executable for the VS Code extension to use. However, the default depot for the conda environment's Julia is still `~/.julia`. To counteract this, I create a sibling folder to the project folder call `/path/to/project/<project name>.depot/` and set `JULIA_DEPOT_PATH` to that location. The main problem is that VS Code has to be started with this environment variable set. Setting it in the `.bash_profile` seems short sighted, so instead I use `direnv` to automatically set the environment variable when I enter the project directory on the command line. I then start VS Code from the command line.

Finally, I have to keep the depot default environment and the project environment synced. I still do all project dependency management in the project environment, but whenever I make a change to that I copy the `Project.toml` and `Manifest.toml` from the project folder to the default depot environment folder. Luckily, it seems that environments are totally characterized by these two files, so that is all we need to keep the environments synced. Since I already added the dependencies to the project environment, they are already in the depot and after syncing the files nothing more needs to be done.

I've thought about setting up a file watcher to automatically sync whenever the project environment files get updated, but I don't feel like they get updated often enough to be worth it.

**Comment by davidanthoff** [comment] 2019-05-12 18:14
We currently don't properly handle environments with the language server. It is on the list of things to fix properly, but not trivial.

**Comment by davidanthoff** [comment] 2019-06-12 04:35
I'm going to close this as a duplicate of https://github.com/JuliaEditorSupport/julia-vscode/issues/732. We now have a PR over at LS that should properly handle the env story in the language server. It doesn't fully work yet, but we are close.

**Closed by davidanthoff** 2019-06-12 04:35 UTC
Labels: area-environments, bug
