### ISSUE TITLE
Support for displaying the output plots within the VsCode editor

### ISSUE THREAD

**Issue by abhi18av** [JuliaEditorSupport/julia-vscode#164] opened 2017-05-26 11:05 UTC
Hello julia-vscode team!

This is a feature request so that the entire code-feedback cycle within the VsCode editor speeds up. Could you provide a functionality like the [pythonVSCode](https://github.com/DonJayamanne/pythonVSCode) plugin ?

This would be awesome, since VsCode does have a better startup time etc. going for itself :)

**Comment by davidanthoff** [comment] 2017-05-29 04:43
Yes, this is on the radar, but not sure when we'll get to this.

**Comment by davidanthoff** [comment] 2017-06-02 19:31
I just published version 0.6.0-alpha.3 [here](https://github.com/JuliaEditorSupport/julia-vscode/releases/tag/v0.6.0-alpha.3) that has a plot pane. If anyone wants to test it and report back it would be great!

**Comment by KristofferC** [comment] 2017-06-02 21:20
Works ok:

![image](https://cloud.githubusercontent.com/assets/1282691/26745274/166023c8-47ea-11e7-891b-7ae70e511b01.png)

Running it again opens up a new plot window though:

![image](https://cloud.githubusercontent.com/assets/1282691/26745284/1d5a9c58-47ea-11e7-9b68-2de2fdc429fb.png)

**Comment by davidanthoff** [comment] 2017-06-02 22:27
@KristofferC Ah, thanks, that is a good bug report! The problem is that I always opened the plot pane in column one, so if you had moved it over to column two, then any new plot would open it again in column 1. In general both of these views then should display all the same plots and you can move through all the plots with the arrows icons etc. and both views will be synced.

[This](https://github.com/JuliaEditorSupport/julia-vscode/commit/b0bb2864ea0f1aec416cf57d15cf309f5f7acefc) commit fixes this, so that a normal plot command no longer opens a new plot view.

I think I'll wait with a new alpha release until we have some more new stuff, if that is ok. For now you can just close one of the views whenever a second one opens up, that should be harmless.

Another thing: right now I first look for a svg representation and use that if available, and the fallback is png. I've seen some discussion over in other plotting packages/IJulia etc. where people seem to prefer png as the better format. Do you have any opinion about that? It is easily changed...

**Comment by KristofferC** [comment] 2017-06-03 07:59
To me SVG should clearly be prioritized since it supports vector graphics and can support interactivity.

**Comment by davidanthoff** [comment] 2017-06-08 16:19
Ok, closing this because this is done :)

**Closed** 2017-06-08 16:19 UTC
Labels: enhancement

**Comment by abhi18av** [comment] 2017-06-08 16:22
Yup, and this works really well too. 👍
