### ISSUE TITLE
Request textDocument/hover failed.

### ISSUE THREAD

**Issue by MFairley** [JuliaEditorSupport/julia-vscode#411] opened 2017-11-25 01:06 UTC
Mac OS High Sierra 10.13.1
VS Code Version 1.18.1 (1.18.1)
Julia extension version: 0.8.1

Output from Julia Language Server

[Error - 17:03:30] Request textDocument/hover failed.
Error: Connection got disposed.
	at Object.dispose (/Users/mfairley/.vscode/extensions/julialang.language-julia-0.8.1/node_modules/vscode-jsonrpc/lib/main.js:825:25)
	at Object.dispose (/Users/mfairley/.vscode/extensions/julialang.language-julia-0.8.1/node_modules/vscode-languageclient/lib/client.js:57:35)
	at LanguageClient.handleConnectionClosed (/Users/mfairley/.vscode/extensions/julialang.language-julia-0.8.1/node_modules/vscode-languageclient/lib/client.js:1864:38)
	at LanguageClient.handleConnectionClosed (/Users/mfairley/.vscode/extensions/julialang.language-julia-0.8.1/node_modules/vscode-languageclient/lib/main.js:106:15)
	at closeHandler (/Users/mfairley/.vscode/extensions/julialang.language-julia-0.8.1/node_modules/vscode-languageclient/lib/client.js:1852:18)
	at CallbackList.invoke (/Users/mfairley/.vscode/extensions/julialang.language-julia-0.8.1/node_modules/vscode-jsonrpc/lib/events.js:71:39)
	at Emitter.fire (/Users/mfairley/.vscode/extensions/julialang.language-julia-0.8.1/node_modules/vscode-jsonrpc/lib/events.js:135:36)
	at closeHandler (/Users/mfairley/.vscode/extensions/julialang.language-julia-0.8.1/node_modules/vscode-jsonrpc/lib/main.js:221:26)
	at CallbackList.invoke (/Users/mfairley/.vscode/extensions/julialang.language-julia-0.8.1/node_modules/vscode-jsonrpc/lib/events.js:71:39)
	at Emitter.fire (/Users/mfairley/.vscode/extensions/julialang.language-julia-0.8.1/node_modules/vscode-jsonrpc/lib/events.js:135:36)
INFO: parsed /Users/mfairley/Source/mse310/online_lp.jl

**Comment by davidanthoff** [comment] 2017-11-26 19:33
I'm getting errors like that a fair bit as well. But I'm at a loss how to debug them with these new logs that don't actually show what is going on...

**Comment by ZacLN** [comment] 2017-11-26 19:59
I've started redirecting stderr to a log file for easily reproducible errors, though this is not a general solution

**Comment by davidanthoff** [comment] 2017-11-26 20:22
Maybe we could at least enable that whenever we run in debug mode?

**Comment by davidanthoff** [comment] 2018-01-06 05:33
So, I think the plan for this one should be that we ship a v0.10.0 beta that has the crash reporting in it. @MFairley, it would be great if you could install that beta once it is out and enable the crash reporting, and hopefully that will send us a stack trace that has enough information for us to figure out the root cause.

**Comment by davidanthoff** [comment] 2018-01-13 23:27
Ok, I'm going to close this for now, and will assume that we'll just get some stack traces via telemetry that will help us find the root cause.

**Closed by davidanthoff** 2018-01-13 23:27 UTC
Labels: bug, needs more info
